version: "3"
services:
  rabbitmq:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    ports:
      - 5672:5672
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=my_vhost