using System.Text;

namespace AMQPProtocolGenerators;

public static class ClassGenerator
{
    public static void GenerateDefinition(ClassDef klass, string path, long version)
    {
        var builder = new StringBuilder();
        builder.AppendLine("namespace AMQPClient.Protocol.Classes;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Generated by AMQPProtocolGenerators application. Class represents \"{klass.Name}\" from AMQP protocol.");
        builder.AppendLine($"/// Version {version}");
        builder.AppendLine("/// <see href=\"..\\AMQPProtocolGenerators\\AMQPProtocolGenerators.csproj\" />");
        builder.AppendLine("/// </summary>");
        
        builder.AppendLine($"public static class {StrFormatUtils.ToPascalCase(klass.Name)} {{");

        foreach (var method in klass.Methods)
        {
            var definition = MethodGenerator.GenerateDefinition(klass, method);
            builder.Append(definition);
            builder.AppendLine();
        }

        builder.AppendLine("}");

        File.WriteAllText(path + "/" + StrFormatUtils.ToPascalCase($"{klass.Name}") + ".cs", builder.ToString());
    }
}