namespace AMQPClient.Protocol.Classes;

/// <summary>
/// Generated by AMQPProtocolGenerators application. Class represents "channel" from AMQP protocol.
/// Version 1719732113823
/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
/// </summary>
public static class Channel {
	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "open" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Open : IFrameMethod {
		public short SourceClassId => 20;
		public short SourceMethodId => 10;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public string Reserved1 { get; set; }= "";

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShortStr(Reserved1);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			Reserved1 = reader.ReadShortStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "open-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class OpenOk : IFrameMethod {
		public short SourceClassId => 20;
		public short SourceMethodId => 11;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public string Reserved1 { get; set; }= "";

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteLongStr(Reserved1);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			Reserved1 = reader.ReadLongStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "flow" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Flow : IFrameMethod {
		public short SourceClassId => 20;
		public short SourceMethodId => 20;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public bool Active { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteBit((byte)(Active ? 1 : 0), false);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			var flags = reader.ReadByte();
			Active = (flags & 1) > 0;
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "flow-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class FlowOk : IFrameMethod {
		public short SourceClassId => 20;
		public short SourceMethodId => 21;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public bool Active { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteBit((byte)(Active ? 1 : 0), false);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			var flags = reader.ReadByte();
			Active = (flags & 1) > 0;
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "close" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Close : IFrameMethod {
		public short SourceClassId => 20;
		public short SourceMethodId => 40;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public short ReplyCode { get; set; }
		public string ReplyText { get; set; }
		public short ClassId { get; set; }
		public short MethodId { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShort(ReplyCode);
			writer.WriteShortStr(ReplyText);
			writer.WriteShort(ClassId);
			writer.WriteShort(MethodId);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			ReplyCode = reader.ReadShort();
			ReplyText = reader.ReadShortStr();
			ClassId = reader.ReadShort();
			MethodId = reader.ReadShort();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "close-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class CloseOk : IFrameMethod {
		public short SourceClassId => 20;
		public short SourceMethodId => 41;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
		}
	}

}
