namespace AMQPClient.Protocol.Classes;

/// <summary>
/// Generated by AMQPProtocolGenerators application. Class represents "connection" from AMQP protocol.
/// Version 1719732113823
/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
/// </summary>
public static class Connection {
	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "start" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Start : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 10;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public byte VersionMajor { get; set; }
		public byte VersionMinor { get; set; }
		public Dictionary<string, object> ServerProperties { get; set; }
		public string Mechanisms { get; set; }
		public string Locales { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteByte(VersionMajor);
			writer.WriteByte(VersionMinor);
			writer.WriteFieldTable(ServerProperties);
			writer.WriteLongStr(Mechanisms);
			writer.WriteLongStr(Locales);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			VersionMajor = reader.ReadByte();
			VersionMinor = reader.ReadByte();
			ServerProperties = reader.ReadFieldTable();
			Mechanisms = reader.ReadLongStr();
			Locales = reader.ReadLongStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "start-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class StartOk : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 11;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public Dictionary<string, object> ClientProperties { get; set; }
		public string Mechanism { get; set; }
		public string Response { get; set; }
		public string Locale { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteFieldTable(ClientProperties);
			writer.WriteShortStr(Mechanism);
			writer.WriteLongStr(Response);
			writer.WriteShortStr(Locale);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			ClientProperties = reader.ReadFieldTable();
			Mechanism = reader.ReadShortStr();
			Response = reader.ReadLongStr();
			Locale = reader.ReadShortStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "secure" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Secure : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 20;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public string Challenge { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteLongStr(Challenge);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			Challenge = reader.ReadLongStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "secure-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class SecureOk : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 21;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public string Response { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteLongStr(Response);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			Response = reader.ReadLongStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "tune" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Tune : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 30;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public short ChannelMax { get; set; }
		public int FrameMax { get; set; }
		public short Heartbeat { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShort(ChannelMax);
			writer.WriteInt(FrameMax);
			writer.WriteShort(Heartbeat);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			ChannelMax = reader.ReadShort();
			FrameMax = reader.ReadInt();
			Heartbeat = reader.ReadShort();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "tune-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class TuneOk : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 31;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public short ChannelMax { get; set; }
		public int FrameMax { get; set; }
		public short Heartbeat { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShort(ChannelMax);
			writer.WriteInt(FrameMax);
			writer.WriteShort(Heartbeat);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			ChannelMax = reader.ReadShort();
			FrameMax = reader.ReadInt();
			Heartbeat = reader.ReadShort();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "open" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Open : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 40;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public string VirtualHost { get; set; }
		public string Reserved1 { get; set; }= "";
		public bool Reserved2 { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShortStr(VirtualHost);
			writer.WriteShortStr(Reserved1);
			writer.WriteBit((byte)(Reserved2 ? 1 : 0), false);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			VirtualHost = reader.ReadShortStr();
			Reserved1 = reader.ReadShortStr();
			var flags = reader.ReadByte();
			Reserved2 = (flags & 1) > 0;
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "open-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class OpenOk : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 41;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public string Reserved1 { get; set; }= "";

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShortStr(Reserved1);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			Reserved1 = reader.ReadShortStr();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "close" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class Close : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 50;
		public bool IsAsyncResponse => false;
		public bool HasBody => false;

		public short ReplyCode { get; set; }
		public string ReplyText { get; set; }
		public short ClassId { get; set; }
		public short MethodId { get; set; }

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			writer.WriteShort(ReplyCode);
			writer.WriteShortStr(ReplyText);
			writer.WriteShort(ClassId);
			writer.WriteShort(MethodId);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
			ReplyCode = reader.ReadShort();
			ReplyText = reader.ReadShortStr();
			ClassId = reader.ReadShort();
			MethodId = reader.ReadShort();
		}
	}

	/// <summary>
	/// Generated by AMQPProtocolGenerators application. Method represents "close-ok" from AMQP protocol.
	/// <see href="..\AMQPProtocolGenerators\AMQPProtocolGenerators.csproj" />
	/// </summary>
	public class CloseOk : IFrameMethod {
		public short SourceClassId => 10;
		public short SourceMethodId => 51;
		public bool IsAsyncResponse => true;
		public bool HasBody => false;

		public byte[] Serialize() {
			var writer = new BinWriter();
			writer.WriteShort(SourceClassId);
			writer.WriteShort(SourceMethodId);
			return writer.ToArray();
		}

		public void Deserialize(byte[] bytes) {
			var reader = new BinReader(bytes);
			reader.ReadShort();
			reader.ReadShort();
		}
	}

}
